### ISSUE TITLE
Objects behind plane also reflected

### ISSUE THREAD

**Issue by marijneken** [keijiro/AdamPlaneReflection#2]
Hi, this looks great and I was thinking of using this as a mirror. There are other implementations for that, but they all seem to have issues. Sadly, I noticed there is also a "problem" with this implementation.
Unless I'm doing something wrong, it seems that objects placed behind the reflecting plane are also reflected. I thought it might be related to the clipping settings, but I found no way of getting "correct" reflections.
Is this an easy fix? Or is this a result of this particular implementation and fundamentally can't be fixed?

**Comment by keijiro** [comment]
I guess that it can be fixed in some way but have no idea about how to fix it.

I'd admit that I have no motivation to fix it because better planar reflection is available with HDRP.

**Comment by marijneken** [comment]
Ah I fully understand. Yes, I did notice the new planar reflection in HDRP. Sadly I don't think I can switch my project to the latest Unity because of plugins that most likely will break. I guess with time I'd be able to switch. Thanks for the response.

**Comment by Flavelius** [comment]
For anyone else looking for a solution, it's a custom shader for all the objects that are intersecting.
The Script already takes care of globally setting the parameters up.
Here's a simple example:
```
Shader "Custom/ReflectionClipped"
{
    Properties
    {
        _Color ("Color", Color) = (1,1,1,1)
        _MainTex ("Albedo (RGB)", 2D) = "white" {}
        _Glossiness ("Smoothness", Range(0,1)) = 0.5
        _Metallic ("Metallic", Range(0,1)) = 0.0
    }
    SubShader
    {
        Tags
        {
            "RenderType"="Opaque"
        }

        LOD 200
        CGPROGRAM

        #pragma surface surf Standard fullforwardshadows addshadow
        #pragma target 3.0
        #pragma multi_compile _ PLANE_REFLECTION_USER_CLIPPLANE

        uniform float4 _PlaneReflectionClipPlane;
        sampler2D _MainTex;

        struct Input
        {
            float2 uv_MainTex;
            float3 worldPos;
        };

        half _Glossiness;
        half _Metallic;
        fixed4 _Color;

        void surf(Input IN, inout SurfaceOutputStandard o)
        {
            fixed4 c = tex2D(_MainTex, IN.uv_MainTex);
            #ifdef PLANE_REFLECTION_USER_CLIPPLANE
            float pointToPlaneDist = dot(IN.worldPos, _PlaneReflectionClipPlane.xyz) + _PlaneReflectionClipPlane.w;
            clip(pointToPlaneDist);
            #endif
            o.Albedo = c.rgb;
            o.Metallic = _Metallic;
            o.Smoothness = _Glossiness;
            o.Alpha = c.a;
        }
        ENDCG
    }
    FallBack "Standard"
}
```
